### ISSUE TITLE
Inline dnt-helper

### ISSUE THREAD

**Issue by schalkneethling** [mdn/mdn-fiori#31] opened 2018-07-11 15:45 UTC
The `dnt-helper` utility almost never changes and it currently blocks rendering because of the HTTP request. It is therefore best to uglify and inline directly in the head of the document.

**Comment by schalkneethling** [comment] 2018-07-12 15:33
Pull request: https://github.com/mozilla/kuma/pull/4881

**Comment by jwhitlock** [comment] 2018-07-26 00:05
Duplicate of https://github.com/mdn/sprints/issues/257

**Closed by jwhitlock** 2018-07-26 00:05 UTC
Labels: P1, cf:High, performance
